# Generated by Django 5.1.2 on 2024-11-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0003_alter_schoolclass_class_teacher'),
        ('teachers_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassTeacher',
        ),
    ]
