# Generated by Django 5.1.2 on 2024-11-26 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0002_initial'),
        ('teachers_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='class_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers_app.teacher'),
        ),
    ]
