# Generated by Django 5.1.2 on 2024-11-28 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0003_alter_schoolclass_class_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.student')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='fees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_fees', to='students_app.fee'),
        ),
    ]
