# Generated by Django 5.1.2 on 2024-11-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0004_fee_alter_student_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
