# Generated by Django 5.1.2 on 2024-12-03 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0005_fee_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='status',
        ),
        migrations.AddField(
            model_name='fee',
            name='class_fee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students_app.schoolclass'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='fees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_fees', to='students_app.fee'),
        ),
    ]
