# Generated by Django 5.1.2 on 2024-12-03 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0006_remove_fee_amount_paid_remove_fee_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fees',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school_fees', to='students_app.fee'),
            preserve_default=False,
        ),
    ]
