# Generated by Django 5.1.2 on 2024-12-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0007_alter_student_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fee',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
