# Generated by Django 5.1.2 on 2024-12-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0008_fee_amount_paid_fee_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='student',
        ),
    ]
