# Generated by Django 5.1.2 on 2024-12-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0009_remove_fee_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='amount_paid',
        ),
        migrations.AddField(
            model_name='student',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
