# Generated by Django 5.1.2 on 2024-12-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0010_remove_fee_amount_paid_student_amount_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='date',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='status',
        ),
    ]
